Feature/hero
BillieHoup/8UY_A_TANK pull request #2
Opened 2023-08-10 22:05 UTC by Jaroslaav13

2023-08-10 22:12 UTC, Jaroslaav13 commented on src/css/hero.css
>  .hero-section{
Не могу понять почему изображение не растягивается на всю секцию:(((((

2023-08-10 22:57 UTC, BillieHoup requested changes

2023-08-10 22:57 UTC, BillieHoup commented on src/css/hero.css
> -.container {}
переіменуй клас на hero-container щоб він не конфліктував з іншими аналогічними класами

2023-08-10 22:57 UTC, BillieHoup commented on src/css/hero.css
> +        background-position: center;
background-position: 0px 0px; має виставити зображення правильно

2023-08-10 22:57 UTC, BillieHoup commented on src/css/hero.css
>  .hero-box-first {}
локальний сервер може сваритись на пусті класи, тому їх краще видаляти поки в них нічого немає

2023-08-10 22:57 UTC, BillieHoup commented on src/partials/hero.html
> +<secnion class="hero-section">
section, а не sencion)

2023-08-10 22:57 UTC, BillieHoup commented on src/css/hero.css
>  }
і можеш задати верхній та нижній паддінги саме на цей клас щоб збільшити розмір картинки

2023-08-11 12:51 UTC, BillieHoup approved these changes

2023-08-11 12:51 UTC, merged